const nodemailer = require('nodemailer');


// pdfStream is the stream generated by html-pdf & certificate is the actual object 
const emailCertificate = async (pdfStream, certificate)=>{
    try{
		const pdfName=certificate.name+'_certificate.pdf';
        const transporter=nodemailer.createTransport({
            service:"yahoo",
            auth:{
                user:process.env.USER,
                pass:process.env.PASSWORD
            },
        });
    
        const info=await transporter.sendMail({
            from:`"CertificateVerifier" <${process.env.USER}>`, // sender address
            to: certificate.email,
            subject: "Certificate of Internship", // subject line
            text: 'Your Certificate of Internship has been generated', // plain text body
            html: '<p>Your Internship Certificate has been generated. Check attachment to download the same.</p>', //html body
            attachments:[
                {   // stream as an attachment
                            filename: pdfName,
                            content: pdfStream
                       },
            ]
        });
        
        return info;
    }
    catch(err){
        console.log(err);
        throw new Error('Unable to email certificate');
    }
}

module.exports={
	emailCertificate
}